export const dungeons = [
  {
    id: 1,
    name: "Райские небеса",
    description: "Данж с небесными испытаниями",
    imageUrl: "/card/dungeon/Heaven/Heaven.jpg",
    energy: 10,
    difficulty: 12,
    cash: 100,
  },
  {
    id: 2,
    name: "Корабль призраков",
    description: "Загадочный корабль, дрейфующий в вечной мгле",
    imageUrl: "/card/dungeon/GhostShip/A ghost ship.png",
    energy: 15,
    difficulty: 18,
    cash: 200,
  },
  {
    id: 3,
    name: "База утопленника",
    description: "Тайная база, скрытая под водой",
    imageUrl: "/card/dungeon/DrowningBasement/Drowning_basement.png",
    energy: 20,
    difficulty: 25,
    cash: 300,
  },
  {
    id: 4,
    name: "Сад Эдема",
    description: "Скрытый оазис с древними тайнами",
    imageUrl: "/card/dungeon/GardenOfEden/Garden of Eden.png",
    energy: 18,
    difficulty: 22,
    cash: 250,
  },
  {
    id: 5,
    name: "Дом поклонения",
    description: "Священное место, защищенное древними стражами",
    imageUrl: "/card/dungeon/HouseOfWorship/House of worship.png",
    energy: 12,
    difficulty: 15,
    cash: 150,
  },
  {
    id: 6,
    name: "Площадь пиратов",
    description: "Место встреч морских разбойников",
    imageUrl: "/card/dungeon/PirateSquare/Pirate_Square.jpg",
    energy: 16,
    difficulty: 20,
    cash: 220,
  },
  {
    id: 7,
    name: "Кракен",
    description: "Морское чудовище охраняет вход в этот данж",
    imageUrl: "/card/dungeon/TheKraken/The kraken.png",
    energy: 25,
    difficulty: 30,
    cash: 350,
  },
  {
    id: 8,
    name: "Арена викингов",
    description: "Битвы сильнейших воинов древности",
    imageUrl: "/card/dungeon/VikingArena/Viking Arena.png",
    energy: 20,
    difficulty: 28,
    cash: 300,
  },
  {
    id: 9,
    name: "Древо мудрости",
    description: "Легендарное дерево, дарующее знания и силу",
    imageUrl: "/card/dungeon/WisdomTree/Wisdom Tree.png",
    energy: 14,
    difficulty: 17,
    cash: 180,
  },
];
